trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build stage'
    jobs:
      - job: Build
        displayName: 'Build job'
        steps:
          - script: |
              # Commands for building the web application
              # For example:
              npm install
              npm run build
            displayName: 'Build'

  - stage: Test
    displayName: 'Test stage'
    jobs:
      - job: Test
        displayName: 'Test job'
        steps:
          - script: |
              # Commands for running automated tests
              # For example:
              npm test
            displayName: 'Run Tests'

  - stage: Deploy
    displayName: 'Deploy stage'
    jobs:
      - job: Deploy
        displayName: 'Deploy job'
        steps:
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: 'saiid211/new_project:$(Build.BuildId)'

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: 'push'
              repository: 'saiid211/new_project'
              tags: '$(Build.BuildId)'
